
## Using Promises with Then() and Catch()
- The __then()__ and __catch()__ methods are used to handle the results of __Promises__ once they have finished pending.
- The __then()__ method is used to handle __resolved__ Promises.
- The __catch()__ method is used to handle __rejected__ Promises.
- Both of these methods use callback functions.
- The callback functions should each have one argument representing the Promise result.

<kbd>Promise w/Then()_Catch()</kbd>            
![](/images/Promise.png)


```
    var promise = new Promise(function() {
      
      //do stuff
     
     var isSuccessful = true;
      setTimeout(function() {                 //asynchronous process after 5 secs
        if(isSuccessful) {                    //if everything went ok
            resolve('success');
        }//if successful
        else {                                //if something went wrong
            reject(Error('failure'));
        }//else
      
      },5000);
    
    
    }); //promise
    
```


<kbd>promise status changes from pending to resolved after 5 seconds</kbd>
```
    
    promise.then(function(val) {      //val represents the fulfillment value
        
        console.log(val);             //logs 'success' since promise resolved
        
    }).catch(function(val) {          //val represents the rejection value
    
        console.log(val);             //doesnt happened since promise never rejected
    
    });

```

### Using Promises with Then( onSuccess, onFailure)
The __then()__ method can be called with a success callback and a failure callback, as an alternative to using the __then()__ and __catch()__ methods.











